server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmstest?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11223344


logging:
  level:
    com:
      dai:
        wms:
          mapper: trace
    org:
      mybatis: trace
      mybatis.spring: trace
    org.springframework.jdbc.core: trace