server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WarehouseManagement?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11223344